spring:
  redis:
    ssl: false
    host: 127.0.0.1
    port: 6380
    database: 0
    timeout: 1000
    password:
    lettuce:
      pool:
        max-active: 100
        max-wait: -1
        max-idle: 20
        min-idle: 0